## **Problem Statement**

*   The dataset contains daily trading data for multiple global companies, including fields such as Open, High, Low, Close, Volume, Industry_Tag, Brand_Name, and other relevant stock indicators, categorized by industry and country.

*   The goal is to perform an in-depth stock market analysis using Pandas, focusing on data cleaning, daily return calculations, volatility analysis, industry trends, and correlation between brands and sectors using visualization tools.


*   After implementation, the analysis highlights the most volatile industries, top-performing brands and provides clear visual insights into market trends and inter-stock relationships, demonstrating effective data wrangling and exploratory analysis on real-world stock data.

## **Dataset Info**


**Date:** The date of the stock price data.

**Open:** The opening price of the stock on that date.

**High:** The highest price the stock reached during the trading day.

**Low:** The lowest price the stock reached during the trading day.

**Close:** The closing price of the stock on that date.

**Volume:** The trading volume, i.e., the number of shares traded on that date.

**Brand_Name:** The name of the brand or company.

**Ticker:** Ticker symbol for the stock.

**Industry_Tag:** The industry category or sector to which the brand belongs.

**Country:** The country where the brand is headquartered or primarily operates.

## **Import Libraries**

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings('ignore')

## **Load Data**

In [ ]:
df = pd.read_csv('/content/World_Stock_Prices_Dataset.csv')

## **Dataset Overview & Structure**

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN
1,2025-03-20 00:00:00-04:00,131.100006,132.289993,130.210007,130.509995,378500,0.0,0.0,lvmh,LVMUY,luxury goods,france,NaN
2,2025-03-20 00:00:00-04:00,236.559998,241.759995,236.199997,239.009995,8321600,0.0,0.0,jpmorgan chase & co,JPM,finance,usa,NaN
3,2025-03-20 00:00:00-04:00,60.480000,61.020000,60.340000,60.619999,16503100,0.0,0.0,cisco,CSCO,technology,usa,NaN
4,2025-03-20 00:00:00-04:00,59.020000,59.290001,58.689999,59.230000,2840400,0.0,0.0,unilever,UL,consumer goods,netherlands,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2000-01-03 00:00:00-05:00,13.822670,13.822670,13.675379,13.720699,48000,0.0,0.0,honda,HMC,automotive,japan,NaN
305210,2000-01-03 00:00:00-05:00,3.990652,4.061914,3.848129,3.990652,134500,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305211,2000-01-03 00:00:00-05:00,31.512873,31.512873,30.431443,30.799129,6057400,0.0,0.0,costco,COST,retail,usa,NaN
305212,2000-01-03 00:00:00-05:00,38.147537,38.255972,35.935457,37.496925,53076000,0.0,0.0,cisco,CSCO,technology,usa,NaN
305213,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN

In [ ]:
df.shape

(305214, 13)

#### **Identifying key columns and understanding data types**

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Capital Gains'],
      dtype='object')

In [ ]:
df.dtypes

Date              object
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
Dividends        float64
Stock Splits     float64
Brand_Name        object
Ticker            object
Industry_Tag      object
Country           object
Capital Gains    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           305214 non-null  object
 1   Open           305214 non-null  float64
 2   High           305214 non-null  float64
 3   Low            305214 non-null  float64
 4   Close          305214 non-null  float64
 5   Volume         305214 non-null  int64
 6   Dividends      305214 non-null  float64
 7   Stock Splits   305214 non-null  float64
 8   Brand_Name     305214 non-null  object
 9   Ticker         305214 non-null  object
 10  Industry_Tag   305214 non-null  object
 11  Country        305214 non-null  object
 12  Capital Gains  2 non-null       float64
dtypes: float64(7), int64(1), object(5)
memory usage: 30.3+ MB

## **Data Cleaning**

Sorting the data in ascendind order

In [ ]:
df = df.sort_values(by='Date').reset_index(drop=True)

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2000-01-03 00:00:00-05:00,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN
1,2000-01-03 00:00:00-05:00,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,NaN
2,2000-01-03 00:00:00-05:00,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,NaN
3,2000-01-03 00:00:00-05:00,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,NaN
4,2000-01-03 00:00:00-05:00,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
305209,2025-03-20 00:00:00-04:00,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,NaN
305210,2025-03-20 00:00:00-04:00,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,NaN
305211,2025-03-20 00:00:00-04:00,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,NaN
305212,2025-03-20 00:00:00-04:00,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,NaN
305213,2025-03-20 00:00:00-04:00,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,NaN

Fix date column

In [ ]:
df['Date'] = pd.to_datetime(df['Date'],utc = True).dt.date

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Capital Gains
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,NaN

### **Standardizing Categorical Data**

Before moving to analysis, ensure data
consistency in categorical values:
Checking key categorical columns prevents errors in grouping, filtering, and aggregations

In [ ]:
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['Date', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country']

In [ ]:
df['Brand_Name'].unique()

array(['american eagle outfitters', 'amd', 'microsoft', 'target',
       'southwest airlines', 'johnson & johnson', 'toyota', 'nike',
       'the coca-cola company', 'colgate palmolive', 'starbucks',
       'jpmorgan chase & co', 'logitech', 'the walt disney company',
       'philips', 'procter & gamble', 'nordstrom', 'cisco', '3m',
       'costco', 'nintendo', 'honda', 'foot locker', 'apple', 'nvidia',
       'the home depot', 'hershey company', 'fedex', 'american express',
       "mcdonald's", 'marriott', 'amazon', 'adobe', 'unilever', 'netflix',
       'salesforce / slack', 'google', 'chipotle', 'lvmh', 'crocs',
       'mastercard', 'adidas', 'delta air lines', 'visa', 'bmw group',
       'ubisoft', 'porsche', 'tesla', 'puma', 'hilton', 'shopify',
       'block', 'spotify', 'pinterest', 'zoom video communications',
       'uber', 'peloton', 'zoominfo', 'airbnb', 'roblox', 'coinbase'],
      dtype=object)

In [ ]:
df['Brand_Name'].nunique()

61

In [ ]:
df['Ticker'].unique()

array(['AEO', 'AMD', 'MSFT', 'TGT', 'LUV', 'JNJ', 'TM', 'NKE', 'KO', 'CL',
       'SBUX', 'JPM', 'LOGI', 'DIS', 'PHG', 'PG', 'JWN', 'CSCO', 'MMM',
       'COST', 'NTDOY', 'HMC', 'FL', 'AAPL', 'NVDA', 'HD', 'HSY', 'FDX',
       'AXP', 'MCD', 'MAR', 'AMZN', 'ADBE', 'UL', 'NFLX', 'CRM', 'GOOGL',
       'CMG', 'LVMUY', 'CROX', 'MA', 'ADDYY', 'DAL', 'V', 'BAMXF',
       'UBSFY', 'POAHY', 'TSLA', 'PMMAF', 'HLT', 'SHOP', 'SQ', 'SPOT',
       'PINS', 'ZM', 'UBER', 'PTON', 'ZI', 'ABNB', 'RBLX', 'COIN'],
      dtype=object)

In [ ]:
df['Ticker'].nunique()

61

In [ ]:
df['Industry_Tag'].unique()

array(['apparel', 'technology', 'retail', 'aviation', 'healthcare',
       'automotive', 'food & beverage', 'consumer goods', 'finance',
       'entertainment', 'manufacturing', 'gaming', 'footwear',
       'logistics', 'food', 'hospitality', 'e-commerce', 'luxury goods',
       'financial services', 'music', 'social media', 'fitness',
       'cryptocurrency'], dtype=object)

In [ ]:
df['Industry_Tag'].nunique()

23

In [ ]:
df['Country'].unique()

array(['usa', 'japan', 'switzerland', 'netherlands', 'france', 'germany',
       'canada'], dtype=object)

In [ ]:
df['Country'].nunique()

7

### **Handling Missing Data**

In [ ]:
df.isna().sum()

Date                  0
Open                  0
High                  0
Low                   0
Close                 0
Volume                0
Dividends             0
Stock Splits          0
Brand_Name            0
Ticker                0
Industry_Tag          0
Country               0
Capital Gains    305212
dtype: int64

In [ ]:
df.drop('Capital Gains',inplace=True,axis=1)

In [ ]:
df.isna().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Brand_Name      0
Ticker          0
Industry_Tag    0
Country         0
dtype: int64

### **Handling Duplicated Data**

In [ ]:
df.duplicated().sum()

np.int64(0)

### **Data Type Corrections**

**Date** should be converted from **object** to **datetime64** since it is needed for time-series analysis.

In [ ]:
# Optional: convert frequent categorical columns to 'category' type to optimize performance
cat_cols = ['Ticker', 'Brand_Name', 'Industry_Tag', 'Country']
for col in cat_cols:
    df[col] = df[col].astype('category')

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305214 entries, 0 to 305213
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          305214 non-null  datetime64[ns]
 1   Open          305214 non-null  float64
 2   High          305214 non-null  float64
 3   Low           305214 non-null  float64
 4   Close         305214 non-null  float64
 5   Volume        305214 non-null  int64
 6   Dividends     305214 non-null  float64
 7   Stock Splits  305214 non-null  float64
 8   Brand_Name    305214 non-null  category
 9   Ticker        305214 non-null  category
 10  Industry_Tag  305214 non-null  category
 11  Country       305214 non-null  category
dtypes: category(4), datetime64[ns](1), float64(6), int64(1)
memory usage: 19.8 MB

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa

## **Feature Engineering**

To explore time-based trends like weekdays or months.

In [ ]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1

To Measure how much the stock changed compared to the previous day.

In [ ]:
# Percentage change in closing price per company
df['Daily_Return'] = df.groupby('Ticker')['Close'].pct_change()

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,NaN

To capture the volatilty within a day

In [ ]:
df['Price_Range'] = df['High'] - df['Low']

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,NaN,0.366017
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,NaN,0.906250
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,NaN,2.057798
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,NaN,0.800534
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,NaN,0.410015

In [ ]:
df.isna().sum()

Date             0
Open             0
High             0
Low              0
Close            0
Volume           0
Dividends        0
Stock Splits     0
Brand_Name       0
Ticker           0
Industry_Tag     0
Country          0
Year             0
Month            0
Daily_Return    61
Price_Range      0
dtype: int64

NaN for the first record of each stock (Ticker) — there's no previous day to compare.

This is normal and expected for the first row of each group. You can just leave it as-is

In [ ]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends',
       'Stock Splits', 'Brand_Name', 'Ticker', 'Industry_Tag', 'Country',
       'Year', 'Month', 'Daily_Return', 'Price_Range'],
      dtype='object')

# **EDA**

# **Time Series Charts**

## **Time Series Charts part 1**

#### **Stock Price History Charts**

1. Filter data

In [ ]:
ticker = 'AAPL'
stock_data = df[df['Ticker'] == ticker]

2. Plot line chart

In [ ]:
# plot
fig = go.Figure([go.Scatter(x=stock_data['Date'],
                            y=stock_data['Close'],
                            mode='lines', name=ticker)])

#layout
fig.update_layout(title=f'Stock Price History: {ticker}',
                  xaxis_title='Date',
                  yaxis_title='Closing Price',
                  template='plotly_white',
                  height=450,
                  width=1200,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Ticker')
fig.show()

#### **Multiple Stock Comparison**

1. Filter data

In [ ]:
selected_tickers = ['AMZN', 'GOOGL', 'MSFT']
filtered_df = df[df['Ticker'].isin(selected_tickers)]

2. Plot line chart

In [ ]:
fig = go.Figure()
for ticker in selected_tickers:
    stock_data = filtered_df[filtered_df['Ticker'] == ticker]
    fig.add_trace(go.Scatter(x=stock_data['Date'],
                             y=stock_data['Close'],
                             mode='lines',
                             name=ticker))

# Update layout
fig.update_layout(title='Stock Price History: Closing Prices Over Time',
                  xaxis_title='Date',
                  yaxis_title='Closing Price',
                  template='plotly_white',
                  height=450,
                  width=1200,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Ticker')
fig.show()

## **Time Series Charts part 2**

#### **Moving Average Chart**

1. Filter the data

In [ ]:
# Filter for AAPL and sort
aapl_df = df[(df['Ticker'] == 'AAPL') & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')

2. Calculate moving average

In [ ]:
# 50 days moving average
aapl_df['MA_50'] = aapl_df['Close'].rolling(window=50).mean()

# 200 days moving average
aapl_df['MA_200'] = aapl_df['Close'].rolling(window=200).mean()

3. Plot moving average chart

In [ ]:
# Create plot
fig = go.Figure()
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['Close'], mode='lines', name='Close'))
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['MA_50'], mode='lines', name='50-day MA'))
fig.add_trace(go.Scatter(x=aapl_df['Date'], y=aapl_df['MA_200'], mode='lines', name='200-day MA'))

fig.update_layout(title='AAPL - Moving Average Chart',
                  xaxis_title='Date',
                  yaxis_title='Price',
                  template='plotly_white',
                  height=450,
                  width=1200,
                  yaxis=dict(tickformat='$.2f'),
                  legend_title='Line')

fig.show()

#### **Candlestick Charts**

1. Filter data

In [ ]:
# Resample AAPL data to monthly frequency
aapl_df = df[(df['Ticker'] == 'AAPL') & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')
aapl_df.set_index('Date', inplace=True)

2. Resample Montly data

In [ ]:
# Resample to monthly data
monthly_aapl = aapl_df.resample('M').agg({'Open': 'first',
                                          'High': 'max',
                                          'Low': 'min',
                                          'Close': 'last',
                                          'Volume': 'sum'}).reset_index()

3. Plot candlestick chart

In [ ]:
fig = go.Figure(data=[go.Candlestick(x=monthly_aapl['Date'],
                                     open=monthly_aapl['Open'],
                                     high=monthly_aapl['High'],
                                     low=monthly_aapl['Low'],
                                     close=monthly_aapl['Close'],
                                     name='AAPL Monthly')])

fig.update_layout(title='AAPL - Monthly Candlestick Chart (2020-2025)',
                  xaxis_title='Date',
                  yaxis_title='Price',
                  xaxis_rangeslider_visible=True,
                  template='plotly_white',
                  height=500,
                  width=1200,
                  yaxis=dict(tickformat='$.2f'),
                  xaxis=dict(tickformat='%b %Y'))
fig.show()

 # **Return Analysis Charts**

### **Return Analysis Charts part 1**



#### **Daily Returns Distribution**

1. Filter data

In [ ]:
# Plot histogram of daily returns for AAPL
ticker = 'AAPL'
aapl_df = df[df['Ticker'] == ticker]

2. Histogram plot

In [ ]:
fig = px.histogram(aapl_df,
                   x='Daily_Return',
                   nbins=100,
                   title='AAPL - Daily Returns Distribution',
                   labels={'Daily_Return': 'Daily Return (%)'},
                   marginal='box',
                   height=450,
                   width=1200,
                   template='plotly_white')

fig.show()

#### **Cumulative Returns**

1. Calculate Cummulative returns

In [ ]:
aapl_df['Cumulative_Return'] = (1 + aapl_df['Daily_Return']).cumprod()-1
aapl_df.dropna(subset=['Cumulative_Return'],inplace=True)

2. Plot cummulative returns

In [ ]:
fig = px.line(aapl_df,
              x='Date',
              y='Cumulative_Return',
              title='AAPL - Cumulative Returns Over Time',
              labels={'Cumulative_Return': 'Cumulative Return (Growth of $1)'},
              height=450,
              width=1200,
              template='plotly_white')
fig.show()

### **Return Analysis Charts part 2**

#### **Heat Maps of Monthly Returns**

1. Filter the data 5 tech stocks

In [ ]:
# Filter data for 5 tech stocks for 2023
tech_tickers = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META']
tech_df = df[(df['Ticker'].isin(tech_tickers)) & (df['Year'] == 2023)]
tech_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range
268675,2023-01-03,241.432609,244.084512,235.791096,237.956329,25740000,0.0,0.0,microsoft,MSFT,technology,usa,2023,1,-0.001001,8.293417
268686,2023-01-03,129.726523,130.343885,123.642480,124.538658,112117500,0.0,0.0,apple,AAPL,technology,usa,2023,1,-0.037405,6.701404
268715,2023-01-03,85.459999,86.959999,84.209999,85.820000,76706000,0.0,0.0,amazon,AMZN,e-commerce,usa,2023,1,0.021667,2.750000
268717,2023-01-03,89.589996,91.050003,88.519997,89.120003,28131200,0.0,0.0,google,GOOGL,technology,usa,2023,1,0.010087,2.530006
268750,2023-01-04,230.705789,231.291787,224.428629,227.547348,50623400,0.0,0.0,microsoft,MSFT,technology,usa,2023,1,-0.043743,6.863158

2. Calculate Monthly returns for each stock

In [ ]:
# Calculate monthly returns for each stock
result_data = []

for ticker in tech_tickers:
    ticker_data = tech_df[tech_df['Ticker'] == ticker].copy()

    # Group by month
    monthly_groups = ticker_data.groupby(tech_df['Date'].dt.month)

    for month_num, group in monthly_groups:
        month_name = group['Date'].iloc[0].strftime('%b')

        # Get first and last trading day of month
        start_price = group.iloc[0]['Open']
        end_price = group.iloc[-1]['Close']

        # Calculate return
        monthly_return = ((end_price - start_price) / start_price) * 100

        result_data.append({'Ticker': ticker,
                            'Month': month_name,
                            'Month_num': month_num,  # Store month number for sorting
                            'Return': monthly_return})

# Convert to DataFrame
monthly_df = pd.DataFrame(result_data)
monthly_df.head()

  Ticker Month  Month_num     Return
0   AAPL   Jan          1  10.753760
1   AAPL   Feb          2   2.545717
2   AAPL   Mar          3  12.306736
3   AAPL   Apr          4   3.293356
4   AAPL   May          5   4.853006

3. Create Pivot table to generate heatmap

In [ ]:
# Pivot the data for the heatmap
pivot_df = monthly_df.pivot(index='Month_num',
                            columns='Ticker',
                            values='Return')

pivot_df.sort_index(inplace=True)  # Sort by month number

4. Plot heatmap

In [ ]:
# Create month labels in correct order
month_labels = [pd.Timestamp(2023, month, 1).strftime('%b') for month in pivot_df.index]

# Create heatmap
fig = go.Figure(data=go.Heatmap( z=pivot_df.values,
                                x=pivot_df.columns,  # Stock tickers
                                 y=month_labels,      # Month names
                                 colorscale=[[0, 'darkred'], [0.5, 'white'], [1, 'darkgreen']],
                                 zmid=0,
                                 colorbar=dict(
                                     title='Monthly Return (%)',
                                     titleside='right'),
                                 text=np.round(pivot_df.values, 2),
                                 texttemplate='%{text:.2f}%',
                                 textfont={"size":12}))

# Update layout
fig.update_layout(title='Monthly Returns of 5 Tech Stocks (2023)',
                  xaxis_title='Stock Ticker',
                  yaxis_title='Month',
                  height=600,
                  width=1200,
                  xaxis={'side': 'top'})

fig.show()

#### **Returns Boxplots**

In [ ]:
aapl_df = df[(df['Ticker'] == 'AAPL') & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')

# Create boxplot of daily returns grouped by year
fig = px.box(aapl_df,
             x='Year',
             y='Daily_Return',
             title='AAPL - Daily Return Distribution by Year',
             labels={'Daily_Return_%': 'Daily Return (%)'},
             height=450,
             width=1200,
             template='plotly_white')
fig.show()

# **Volume Analysis Charts**

#### **Daily Volume and Moving Average**

1. Filter data

In [ ]:
ticker = 'AAPL'
aapl_df = df[(df['Ticker'] == ticker) & (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')

2. Calulate moving average for 100 days

In [ ]:
# Calculate 20-day volume moving average for AAPL
aapl_df['Volume_MA_100'] = aapl_df['Volume'].rolling(window=100).mean()
aapl_df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range,Volume_MA_100
223526,2020-01-02,72.246685,73.310001,71.990615,73.249031,135480400,0.0,0.0,apple,AAPL,technology,usa,2020,1,0.022816,1.319386,NaN
223618,2020-01-03,72.468602,73.305105,72.310083,72.536888,146322800,0.0,0.0,apple,AAPL,technology,usa,2020,1,-0.009722,0.995022,NaN
223678,2020-01-06,71.649176,73.153905,71.395540,73.114883,118387200,0.0,0.0,apple,AAPL,technology,usa,2020,1,0.007968,1.758365,NaN
223701,2020-01-07,73.124639,73.383150,72.549088,72.771019,108872000,0.0,0.0,apple,AAPL,technology,usa,2020,1,-0.004703,0.834062,NaN
223755,2020-01-08,72.471053,74.246491,72.471053,73.941643,132079200,0.0,0.0,apple,AAPL,technology,usa,2020,1,0.016086,1.775438,NaN

3. Plot Daily volumne and moving average

In [ ]:
fig = go.Figure()

# Daily volume
fig.add_trace(go.Scatter(x=aapl_df['Date'],
                         y=aapl_df['Volume'],
                         name='Daily Volume',
                         mode='lines',
                         line=dict(color='#1f77b4')))

# 100-day moving average of volume
fig.add_trace(go.Scatter(x=aapl_df['Date'],
                         y=aapl_df['Volume_MA_100'],
                         name='100-Day Volume MA',
                         mode='lines',
                         line=dict(color='red', dash='dot')))

# Layout
fig.update_layout(title='AAPL - Volume with 100-Day Moving Average',
                  xaxis_title='Date',
                  yaxis_title='Volume',
                  template='plotly_white',
                  height=500,
                  width=1200,
                  legend=dict(orientation="h", y=1.1, x=0.7))
fig.show()

#### **Volume Grouped Bar Charts : Tech companies yearly volume comparison**

1. Filter data

In [ ]:
# List of tech companies to compare
tech_tickers = ['AAPL', 'MSFT', 'GOOGL']
tech_names = {'AAPL': 'Apple', 'MSFT': 'Microsoft', 'GOOGL': 'Google'}

# Filter data for the selected tech companies from 2020-2025
tech_df = df[(df['Ticker'].isin(tech_tickers)) &
             (df['Year'] >= 2020) & (df['Year'] <= 2025)].sort_values('Date')
tech_df[['Date','Ticker','Volume']].head()

             Date Ticker     Volume
223526 2020-01-02   AAPL  135480400
223541 2020-01-02  GOOGL   27278000
223551 2020-01-02   MSFT   22622100
223604 2020-01-03  GOOGL   23408000
223618 2020-01-03   AAPL  146322800

2. Data Aggrigation

In [ ]:
# Aggregate total volume per year for each company
yearly_volume = tech_df.groupby(['Year', 'Ticker'])['Volume'].sum().reset_index()

# Convert volume to billions for better readability
yearly_volume['Volume_Billions'] = yearly_volume['Volume'] / 1_000_000_000

In [ ]:
# Create a grouped bar chart without any traces
fig = go.Figure()

# Add bars for each company
for i, ticker in enumerate(tech_tickers):
    company_data = yearly_volume[yearly_volume['Ticker'] == ticker]

    fig.add_trace(go.Bar(x=company_data['Year'],
                         y=company_data['Volume_Billions'],
                         name=tech_names[ticker]))

# Simple layout
fig.update_layout(title='Annual Trading Volume: Tech Companies (2020-2025)',
                  xaxis_title='Year',
                  yaxis_title='Volume (Billions)',
                  template='plotly_white',
                  barmode='group',
                  height=500,
                  width=1200,
                  legend=dict(orientation="h", y=1.1, x=0.7))

fig.show()

# **Comparative Analysis Charts**

### **Cumulative returns by industry**

1. Calculate Cumulative Return

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,NaN,0.366017
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,NaN,0.906250
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,NaN,2.057798
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,NaN,0.800534
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,NaN,0.410015

In [ ]:
df['Cumulative_Return'] = (1 + df['Daily_Return']).groupby(df['Ticker']).cumprod() - 1  # Subtract 1 to get actual return percentage

In [ ]:
df.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range,Cumulative_Return
0,2000-01-03,5.731675,5.793975,5.427959,5.482471,5825700,0.0,0.0,american eagle outfitters,AEO,apparel,usa,2000,1,NaN,0.366017,NaN
1,2000-01-03,14.968750,15.593750,14.687500,15.500000,7843200,0.0,0.0,amd,AMD,technology,usa,2000,1,NaN,0.906250,NaN
2,2000-01-03,36.457976,36.846240,34.788441,36.205605,53228400,0.0,0.0,microsoft,MSFT,technology,usa,2000,1,NaN,2.057798,NaN
3,2000-01-03,23.135441,23.295548,22.495014,23.075401,2870400,0.0,0.0,target,TGT,retail,usa,2000,1,NaN,0.800534,NaN
4,2000-01-03,9.653981,9.765803,9.355788,9.467610,3277800,0.0,0.0,southwest airlines,LUV,aviation,usa,2000,1,NaN,0.410015,NaN

In [ ]:
df.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range,Cumulative_Return
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,-0.003365,0.259998,3.452906
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,-0.014021,3.590004,6.389142
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,0.000204,0.859997,0.113636
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,-0.007052,2.750000,3.515631
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,0.004434,12.020019,22.939647

In [ ]:
latest_date = df['Date'].max()
latest_date

Timestamp('2025-03-20 00:00:00')

In [ ]:
latest_returns = df[df['Date'] == latest_date]
latest_returns

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Brand_Name,Ticker,Industry_Tag,Country,Year,Month,Daily_Return,Price_Range,Cumulative_Return
305153,2025-03-20,151.649994,153.649994,151.089996,151.270004,2579000,0.0,0.0,3m,MMM,manufacturing,usa,2025,3,-0.012662,2.559998,5.106280
305154,2025-03-20,168.889999,169.210007,166.029999,167.550003,8785300,0.0,0.0,procter & gamble,PG,consumer goods,usa,2025,3,-0.006051,3.180008,4.856717
305155,2025-03-20,16.299999,16.639999,16.049999,16.049999,2689000,0.0,0.0,foot locker,FL,footwear,usa,2025,3,-0.029625,0.590000,3.055655
305156,2025-03-20,25.980000,26.190001,25.790001,25.879999,760100,0.0,0.0,philips,PHG,technology,netherlands,2025,3,-0.033607,0.400000,0.350836
305157,2025-03-20,24.250000,24.330000,24.250000,24.309999,1399500,0.0,0.0,nordstrom,JWN,retail,usa,2025,3,0.000823,0.080000,2.391369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305209,2025-03-20,17.959999,17.959999,17.700001,17.770000,545600,0.0,0.0,nintendo,NTDOY,gaming,japan,2025,3,-0.003365,0.259998,3.452906
305210,2025-03-20,106.820000,108.970001,105.379997,105.480003,1481100,0.0,0.0,crocs,CROX,footwear,usa,2025,3,-0.014021,3.590004,6.389142
305211,2025-03-20,48.500000,49.349998,48.490002,49.000000,10706600,0.0,0.0,chipotle,CMG,food,usa,2025,3,0.000204,0.859997,0.113636
305212,2025-03-20,104.400002,106.669998,103.919998,104.199997,5853100,0.0,0.0,target,TGT,retail,usa,2025,3,-0.007052,2.750000,3.515631
305213,2025-03-20,386.899994,397.820007,385.799988,389.609985,4003800,0.0,0.0,adobe,ADBE,technology,usa,2025,3,0.004434,12.020019,22.939647

In [ ]:
# Get latest date's cumulative return for each ticker
latest_date = df['Date'].max()
latest_returns = df[df['Date'] == latest_date]

# Average by industry and sort
industry_performance = latest_returns.groupby('Industry_Tag')['Cumulative_Return'].mean().sort_values(ascending=False).reset_index()

# Plot top 5 industries
top5_industries = industry_performance.head(5)

fig = px.bar(
    top5_industries,
    x='Industry_Tag',
    y='Cumulative_Return',
    title='Top 5 Industries by Average Cumulative Return',
    labels={'Cumulative_Return': 'Avg Cumulative Return (%)'}
)

fig.update_layout(xaxis_title='Industry', yaxis_title='Cumulative Return (%)')
fig.update_traces(textposition='outside')

fig.show()

#### **Volatility By Industry**

In [ ]:
industry_volatility = df.groupby('Industry_Tag')['Daily_Return'].std().sort_values(ascending=False).reset_index()
industry_volatility

          Industry_Tag  Daily_Return
0       cryptocurrency      0.054660
1              fitness      0.053093
2         social media      0.039036
3   financial services      0.036033
4             footwear      0.034343
5           e-commerce      0.033112
6         luxury goods      0.030244
7                music      0.029456
8               gaming      0.028599
9           technology      0.028230
10       entertainment      0.027683
11            aviation      0.026852
12             apparel      0.025482
13          automotive      0.022856
14              retail      0.022127
15             finance      0.021495
16         hospitality      0.021458
17                food      0.021273
18           logistics      0.019810
19     food & beverage      0.016468
20       manufacturing      0.015608
21      consumer goods      0.013726
22          healthcare      0.012006

In [ ]:
industry_volatility = df.groupby('Industry_Tag')['Daily_Return'].std().sort_values(ascending=False).reset_index()
industry_volatility.rename(columns={'Daily_Return': 'Volatility'}, inplace=True)

# Select top 5 most volatile industries
top5_volatile = industry_volatility.head(5)

# Plot bar chart
fig = px.bar(
    top5_volatile,
    x='Industry_Tag',
    y='Volatility',
    title='Top 5 Most Volatile Industries',
    labels={'Industry_Tag': 'Industry', 'Volatility': 'Volatility (Std Dev)'},
    template='plotly_white'
)

fig.update_layout(xaxis_tickangle=-30)
fig.show()

In [ ]:
industry_volatility.tail(5)

       Industry_Tag  Volatility
18        logistics    0.019810
19  food & beverage    0.016468
20    manufacturing    0.015608
21   consumer goods    0.013726
22       healthcare    0.012006

In [ ]:
# Select top 5 most stable industries
top5_stable = industry_volatility.tail(5)

# Plot bar chart
fig = px.bar(
    top5_stable,
    x='Industry_Tag',
    y='Volatility',
    title='Top 5 Most Stable Industries',
    labels={'Industry_Tag': 'Industry', 'Volatility': 'Volatility (Std Dev)'},
    template='plotly_white'
)

fig.update_layout(xaxis_tickangle=-30)
fig.show()